console.log("-----------------json------------------");
var json_number = require("./json/number.json");
var json_string1 = require("./json/string1.json");
var json_string2 = require("./json/string2.json");
var json_true = require("./json/true.json");
var json_false = require("./json/false.json");
var json_null = require("./json/null.json");
var json_undefined = require("./json/undefined.json");
var json_date = require("./json/date.json");
var json_function = require("./json/function.json");
var json_object = require("./json/object.json");
var json_array = require("./json/array.json");
var json_regExpString = require("./json/regExpString.json");
var json_regExp = require("./json/regExp.json");
var json_empty = require("./json/empty.json");
var json_execute = require("./json/execute.json");

console.log("-----json_number-------");
console.log(json_number);
console.log("-----json_string-------");
console.log(json_string1);
console.log("-----json_string-------");
console.log(json_string2);
console.log("-----json_true-------");
console.log(json_true);
console.log("-----json_false-------");
console.log(json_false);
console.log("-----json_null-------");
console.log(json_null);
console.log("-----json_undefined-------");
console.log(json_undefined);
console.log("-----json_date-------");
console.log(json_date);
console.log("-----json_function-------");
console.log(json_function);
console.log("-----json_object-------");
console.log(json_object);
console.log("-----json_array-------");
console.log(json_array);
console.log("-----json_regExpString-------");
console.log(json_regExpString);
console.log("-----json_regExp-------");
console.log(json_regExp);
console.log("-----json_empty-------");
console.log(json_empty);
console.log("-----json_execute-------");
console.log(json_execute);

console.log("-----------------js------------------");
var js_number = require("./js/number.js");
var js_string1 = require("./js/string1.js");
var js_string2 = require("./js/string2.js");
var js_true = require("./js/true.js");
var js_false = require("./js/false.js");
var js_null = require("./js/null.js");
var js_undefined = require("./js/undefined.js");
var js_date = require("./js/date.js");
var js_function = require("./js/function.js");
var js_object = require("./js/object.js");
var js_array = require("./js/array.js");
var js_regExpString = require("./js/regExpString.js");
var js_regExp = require("./js/regExp.js");
var js_empty = require("./js/empty.js");
var js_execute = require("./js/execute.js");

console.log("-----js_number-------");
console.log(js_number);
console.log("-----js_string-------");
console.log(js_string1);
console.log("-----js_string-------");
console.log(js_string2);
console.log("-----js_true-------");
console.log(js_true);
console.log("-----js_false-------");
console.log(js_false);
console.log("-----js_null-------");
console.log(js_null);
console.log("-----js_undefined-------");
console.log(js_undefined);
console.log("-----js_date-------");
console.log(js_date);
console.log("-----js_function-------");
console.log(js_function);
console.log("-----js_object-------");
console.log(js_object);
console.log("-----js_array-------");
console.log(js_array);
console.log("-----js_regExpString-------");
console.log(js_regExpString);
console.log("-----js_regExp-------");
console.log(js_regExp);
console.log("-----js_empty-------");
console.log(js_empty);
console.log("-----js_execute-------");
console.log(js_execute);

console.log("-----------------text------------------");
var text_multi = require("./text/multi.text");
console.log("-----text_multi-------");
console.log(text_multi);

console.log("-----------------css------------------");
var css_multi = require("./css/multi.css");
console.log("-----css_multi-------");
console.log(css_multi);